# Generated by Django 4.1 on 2023-07-09 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('first_name', models.CharField(default='unknown', max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=3, null=True)),
                ('is_marrital_status', models.BooleanField()),
                ('email_id', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('job_profile', models.CharField(max_length=50)),
            ],
        ),
    ]
