# Generated by Django 4.1 on 2023-07-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='is_marrital_status',
            new_name='is_marrital',
        ),
    ]
