# Generated by Django 4.1 on 2023-07-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('first_name', models.CharField(default='unknown', max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('blood_group', models.CharField(max_length=3, null=True)),
            ],
        ),
    ]
